### ISSUE TITLE
Error on Export to Idleon Companion

### ISSUE THREAD

**Issue by Luunae** [desophos/idleon-saver#8]
The card_base and card_name dicts are missing definitions for new cards added in the 1.30 party dungeons update, causing Idleon Companion export to fail.

`  File "idleon-saver/scripts/export.py", line 113, in <dictcomp>
    card_names[name]: get_cardtier(name, level)
  KeyError: 'totem'`

I am not sure what entries need added, I worked around this by changing line 98  of export.py to:

`base = card_bases[name] if name in card_bases else 10`

and line 113 to:

`(card_names[name] if name in card_names else name): get_cardtier(name, level)`

This allows for properly exporting to an `idleon_companion.json` file.

**Comment by desophos** [comment]
This should be fixed with the migration to https://github.com/Corbeno/idleon-data, which makes it easy to keep the data up to date. Exporting should fail when a new game version changes the data, but updating idleon-data should be all it takes to get it working again. 

It would be a good idea to clearly display the compatible game version, but that's a separate issue.
